version: '3'

services:
  spring-boot-jpa-app:
    image: spring-boot-rest-docker-image2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    volumes:
      - /data/peopledocker-app